Repository OpenPrinting/cups, pull requests merged in 2020-11, with the labels that each got.

#21 Debian: Install root backends world-readable
  backend/Makefile
  scheduler/cups-deviced.c
  scheduler/job.c
Labels: enhancement, priority-low

#24 Debian: Fix scheduler cupsd.conf load
  scheduler/client.c
Labels: bug, priority-medium

#28 Debian: Let snmp backend also use manufacturer-specific MIBs
  backend/snmp.c
Labels: enhancement, priority-low

#29 Debian: Disable time stamps in conffiles, to avoid ever-changing files in /etc.
  scheduler/classes.c
  scheduler/job.c
  scheduler/printers.c
  scheduler/subscriptions.c
Labels: enhancement, priority-low

#32 Debian: Do not use host names for broadcasting print queues
  scheduler/conf.c
Labels: bug, priority-low

#43 backend,scheduler/ipp.c: Fix 'printer-alert' invalid free
  backend/ipp.c
  scheduler/ipp.c
Labels: bug, priority-high

#40 Debian: Fix fax numbers supplied via GTK print dialog
  backend/ipp.c
Labels: bug, priority-low

#41 Debian: Let the rastertopwg filter check rounding errors when calculating the page geometry
  filter/rastertopwg.c
Labels: bug, priority-low

#35 Debian: Allow configuration of MaxLogSize at configure-time
  conf/cupsd.conf.in
  config-scripts/cups-defaults.m4
Labels: enhancement, priority-low

#51 [Fedora] cups.service.in: Use 'notify' service type and run after net…
  scheduler/cups.service.in
  scheduler/main.c
Labels: enhancement, platform issue, priority-medium
