Repository OpenPrinting/cups, pull requests merged in 2020-10, with the labels that each got.

#2 Fix leakage of ppd
  ppdc/ppdc-import.cxx
Labels: performance, priority-medium

#6 cups/dests.c: cupsGetNamedDest() - set IPP_STATUS_ERROR_NOT_FOUND err…
  berkeley/lpr.c
  cups/dest.c
  systemv/lp.c
Labels: bug, priority-low

#7 Fix installation of xinetd configuration file for cups-lpd
  scheduler/Makefile
Labels: bug, priority-low

#13 undefined behavior: signed integer overflow
  cups/ppd.c
Labels: bug, priority-low

#12 Fix memory leaks
  scheduler/conf.c
  scheduler/printers.c
Labels: bug, priority-medium

#11 backend/Makefile: Don't use libtool.
  backend/Makefile
Labels: bug, platform issue, priority-low

#1 Prioritize print-color-mode-supported over PWG when creating color mo…
  cups/ppd-cache.c
Labels: enhancement, platform issue, priority-low
