Repository OpenPrinting/cups, pull requests merged in 2021-03, with the labels that each got.

#19 Fix negotiate authentication between CGIs and scheduler
  cups/auth.c
  scheduler/client.c
Labels: bug, investigating, priority-low

#106 making True case-insensitive and correcting documentation for existing clients
  cups/ppd.c
  doc/help/spec-ppd.html
  filter/spec-ppd.shtml
Labels: enhancement, priority-low

#70 add some more ZPL labelsizes
  ppdc/sample.drv
Labels: enhancement, priority-medium

#74 backend/ipp: Change handling of job_canceled
  backend/ipp.c
Labels: bug, priority-low

#110 cups/dest.c: Remove an underscore from queue name
  CHANGES.md
  cups/dest.c
Labels: enhancement, investigating, priority-low

#123 added new translations
  doc/de/index.html.in
  locale/cups_de.po
  templates/da/header.tmpl.in
  templates/da/help-header.tmpl
  templates/de/header.tmpl.in
  templates/es/header.tmpl.in
  templates/es/help-header.tmpl
  templates/fr/header.tmpl.in
  templates/fr/help-header.tmpl
  templates/header.tmpl.in
  templates/help-header.tmpl
  templates/ja/header.tmpl.in
  templates/ja/help-header.tmpl
  templates/pt_BR/header.tmpl.in
  templates/pt_BR/help-header.tmpl
  templates/ru/header.tmpl.in
  templates/ru/help-header.tmpl
Labels: enhancement, priority-low

#122 adding pkgconfig file
  .gitignore
  Makedefs.in
  Makefile
  config-scripts/cups-common.m4
  config-scripts/cups-directories.m4
  config-scripts/cups-dnssd.m4
  config-scripts/cups-gssapi.m4
  config-scripts/cups-tls.m4
  configure
  configure.ac
  cups.pc.in
Labels: enhancement

#128 table header left aligned
  doc/cups.css
Labels: enhancement, priority-low

#143 cups.service.in: Add SYSTEMD_WANTED_BY variable
  CHANGES.md
  config-scripts/cups-defaults.m4
  scheduler/cups.service.in
Labels: enhancement, platform issue, priority-medium

#146 notices in localized index pages adjusted
  doc/da/index.html.in
  doc/de/index.html.in
  doc/es/index.html.in
  doc/fr/index.html.in
  doc/ja/index.html.in
  doc/pt_BR/index.html.in
  doc/ru/index.html.in
Labels: enhancement, priority-low

#154 scheduler/log.c: Use `[Job N]` even for syslog
  CHANGES.md
  scheduler/log.c
Labels: enhancement, priority-low
