Repository OpenPrinting/cups, pull requests merged in 2021-08, with the labels that each got.

#212 Add the Canon PIXMA MP240 to the USB quirk list
  backend/org.cups.usb-quirks
Labels: enhancement, priority-low, platform issue

#223 libcups: Fix unused-function error with SSL disabled
  cups/usersys.c
Labels: enhancement, priority-low, platform issue

#225 Fix build on ancient platforms lacking SHA224
  cups/hash.c
Labels: enhancement, priority-low, platform issue

#228 Fix undefined behavior regarding pData
  backend/usb-darwin.c
Labels: bug, priority-low, platform issue

#209 scheduler/job.c: use gziptoany for raw files (not just raw printers)
  scheduler/job.c
Labels: bug, priority-low

#232 Fix bug that removes language instead of country code
  scheduler/client.c
Labels: bug, priority-low

#233 Prevent writing to NULL if buffer is NULL
  cups/snprintf.c
Labels: bug, priority-low, platform issue

#229 Fall back to /private/tmp on Mac OS X 10.4
  cups/ppd-util.c
  cups/tempfile.c
Labels: enhancement, priority-low, platform issue

#234 Sync improvements from downstream darwin-usb
  backend/usb-darwin.c
Labels: bug, priority-low, platform issue
