Repository OpenPrinting/cups, pull requests merged in 2021-02, with the labels that each got.

#73 Ignore the APPrinterIconPath PPD attribute
  cups/ppd-cache.c
Labels: enhancement, platform issue, priority-low

#88 issue #87 cupsfilter showing particular errors.
  scheduler/cupsfilter.c
Labels: enhancement, priority-low

#109 setting default browsing dependent on env variable
  conf/cupsd.conf.in
Labels: bug, priority-low
