Repository OpenPrinting/cups, pull requests merged in 2021-04, with the labels that each got.

#167 Logging enhancement.
  backend/backend-private.h
  backend/ipp.c
  backend/snmp.c
  backend/testbackend.c
  backend/usb-darwin.c
Labels: bug, enhancement, priority-low

#164 Add cups_da.po (2.3.0)
  locale/cups_da.po
Labels: enhancement, priority-medium

#141 scheduler/cups.service.in: Use nss-user-lookup.target in "After="
  scheduler/cups.service.in
Labels: enhancement, platform issue, priority-low

#179 Use mv with the -f (force) argument in makefiles
  Makedefs.in
Labels: enhancement, priority-low
