Repository OpenPrinting/cups, pull requests merged in 2021-09, with the labels that each got.

#241 Removed last remnants of CUPS_REVISION, since it is not used anymore
  configure
  doc/da/index.html.in
  doc/de/index.html.in
  doc/es/index.html.in
Labels: bug, priority-low

#235 Add _CUPS_NORETURN to missing functions
  cups/tlscheck.c
  ppdc/ppdc.cxx
  ppdc/ppdhtml.cxx
  ppdc/ppdi.cxx
  ppdc/ppdmerge.cxx
  ppdc/ppdpo.cxx
Labels: enhancement, priority-low

#240 Fix path to libcupsimage.so.2 in EPM packaging
  packaging/cups.list.in
Labels: bug, priority-low

#242 CUPS Web UI: Fix uninitialized variable during driver selection
  CHANGES.md
  templates/choose-model.tmpl
Labels: bug, priority-low

#230 Remove redundant code
  cgi-bin/template.c
  cgi-bin/var.c
  cups/auth.c
  cups/getdevices.c
  cups/ipp-file.c
  cups/pwg-media.c
  cups/tls-gnutls.c
  filter/common.c
  filter/rastertohp.c
  scheduler/auth.c
  scheduler/main.c
  scheduler/util.c
  systemv/cancel.c
  systemv/cupstestppd.c
  systemv/lpstat.c
  tools/ippeveps.c
Labels: enhancement, priority-low

#218 choose-model.tmpl: Add warning about drivers deprecation
  CHANGES.md
  cgi-bin/admin.c
  templates/printer-added.tmpl
Labels: enhancement, priority-low

#222 Only include os/availability.h if needed
  cups/versioning.h
Labels: enhancement, priority-low, platform issue

#231 Update Xcode and configure.ac files
  configure.ac
  xcode/CUPS.xcodeproj/project.pbxproj
Labels: investigating

#247 Fix swapped arguments
  ppdc/ppdc-source.cxx
  ppdc/ppdc.cxx
Labels: bug, priority-medium

#249 Fix missing comma
  tools/ippeveprinter.c
Labels: bug, priority-medium

#252 Fix Macro typo
  xcode/config.h
Labels: bug, priority-low, platform issue

#253 Don't use comma after last enum listing
  cups/http.h
Labels: bug, priority-low

#254 Use correct argument name
  notifier/rss.c
Labels: bug, priority-low

#250 scheduler/ipp.c: Change job state to IPP_JOB_HELD when job is restarted with appropriate job-held-until attribute.
  scheduler/ipp.c
Labels: bug, priority-low

#239 fix _cupsGet1284Values
  cups/options.c
Labels: enhancement, priority-low

#264 Expand whitelist for use of "offline-report"
  scheduler/job.c
Labels: enhancement, priority-low
