Repository OpenPrinting/cups, pull requests merged in 2021-11, with the labels that each got.

#286 scheduler/printers.c: Add warning when loading printers
  scheduler/printers.c
Labels: enhancement, priority-medium

#285 cups-compiler.m4: Check for -fstack-protector-strong
  config-scripts/cups-compiler.m4
Labels: enhancement

#287 cups/http-support.c: Apply DigestOptions to RFC 2069 support
  cups/http-support.c
Labels: enhancement, priority-medium

#293 cups/getifaddrs-internal.h: Include versioning.h if ! HAVE_GETIFADDRS
  cups/getifaddrs-internal.h
Labels: bug, priority-medium

#294 Add --with-idle-exit-timeout configure option
  CHANGES.md
  conf/cupsd.conf.in
  config-scripts/cups-defaults.m4
  configure
Labels: enhancement, priority-medium

#298 Add --with-systemd-timeoutstartsec configure option
  CHANGES.md
  config-scripts/cups-defaults.m4
  configure
  scheduler/cups.service.in
Labels: enhancement, priority-medium
