Repository OpenPrinting/cups, pull requests merged in 2022-09, with the labels that each got.

#472 Remove unused variable cupsd_kqueue_changes
  scheduler/select.c
Labels: bug, priority-low

#480 SysEventPipes does not need to be cast to int since it is an integer already
  scheduler/sysman.c
Labels: enhancement, priority-low

#486 scheduler/ipp.c: Ignore some more IPP defaults (fixes #484)
  scheduler/ipp.c
Labels: enhancement, priority-medium
