Repository OpenPrinting/cups, pull requests merged in 2022-11, with the labels that each got.

#532 [Mistake Bug-Fix]: Fix cupsfilter by setting both array elements to -1
  scheduler/cupsfilter.c
Labels: bug, priority-low

#530 Update Xcode Project
  xcode/CUPS.xcodeproj/project.pbxproj
Labels: platform issue

#519 Fix trivial deprecations
  backend/ipp.c
  cups/tls-darwin.c
  cups/usersys.c
  scheduler/sysman.c
Labels: enhancement, priority-low, platform issue

#536 Avoid passing a constant to atoi
  cgi-bin/admin.c
Labels: enhancement, priority-low

#560 Replace deprecated httpConnect function with httpConnect2
  notifier/rss.c
Labels: enhancement, priority-low

#557 Fix ippDeleteValues corner case.
  cups/ipp.c
Labels: bug, priority-medium
