Repository OpenPrinting/cups, pull requests merged in 2022-06, with the labels that each got.

#407 Update config.{sub,guess}
  config.guess
  config.sub
Labels: bug, priority-medium

#353 For local services use "localhost" in device URI of temporary queue
  scheduler/ipp.c
Labels: enhancement, priority-medium, platform issue

#420 scheduler/ipp.c: Allocate device_uri via cupsdSetString()
  CHANGES.md
  scheduler/ipp.c
Labels: bug, priority-high
