Repository OpenPrinting/cups, pull requests merged in 2022-12, with the labels that each got.

#566 Change strncmp parameter
  cups/ppd-cache.c
Labels: bug, priority-high

#565 Update config files to latest version
  config.guess
  config.sub
Labels: enhancement, priority-low, platform issue

#568 Fix compiler warnings about non-null and casting
  backend/ipp.c
  backend/lpd.c
  tools/ippeveps.c
Labels: bug, priority-low

#567 Remove pointless casts
  cups/file.c
  cups/http.c
  cups/ipp-file.c
  cups/raster-interpret.c
  cups/raster-stream.c
Labels: enhancement, priority-low

#570 Update InputSlot selection for photo sizes (fixes #569)
  cups/ppd-cache.c
Labels: bug, priority-medium

#518 Change cupsd.conf to force authentication when accessing administration
  conf/cupsd.conf.in
Labels: enhancement, priority-medium
