Repository OpenPrinting/cups, pull requests merged in 2023-05, with the labels that each got.

#669 UBSan: Array over-read when operating on _fields
  cups/http.c
Labels: bug, priority-medium

#659 Cast to unsigned long instead of long for size_t
  cups/request.c
Labels: priority-low, not a bug

#642 configure: Raise FORTIFY_SOURCE level to 3
  config-scripts/cups-compiler.m4
  configure
Labels: enhancement, priority-low, platform issue

#590 Improve state handling in cases of memory allocation failure
  backend/dnssd.c
  cgi-bin/var.c
  cups/dest.c
  cups/globals.c
  cups/http.c
  cups/ipp.c
  cups/language.c
  cups/ppd-cache.c
  cups/ppd-emit.c
  cups/raster-stream.c
  cups/tls-sspi.c
  scheduler/cert.c
  scheduler/cups-driverd.cxx
  scheduler/job.c
  tools/ippfind.c
Labels: enhancement, priority-medium

#656 Use %u for unsigned, not signed
  backend/dnssd.c
  backend/ipp.c
  backend/lpd.c
  backend/usb-darwin.c
  backend/usb-libusb.c
  cups/auth.c
Labels: bug, priority-low

#687 Fix check for existing color mode setting
  scheduler/printers.c
Labels: bug, priority-high

#686 Use print_ptr instead of print_buffer
  backend/usb-libusb.c
Labels: bug, priority-high, platform issue

#655 Free memory leaked by Darwin's Core Foundation
  backend/usb-darwin.c
  cups/tls-darwin.c
  ppdc/ppdc-catalog.cxx
Labels: investigating

#695 Fix ipptool JSON output
  tools/ipptool.c
Labels: bug, priority-medium

#692 Check that the number of trays is consistent before fetching anymore data
  tools/ippeveprinter.c
Labels: bug, priority-low

#706 Document default repeat interval
  doc/help/man-ipptoolfile.html
  man/ipptoolfile.5
Labels: documentation

#709 Add custom page size values to media-col-database
  scheduler/printers.c
Labels: enhancement, priority-medium
