Repository OpenPrinting/cups, pull requests merged in 2023-01, with the labels that each got.

#578 Increase log level for "Expiring subscriptions..."
  scheduler/subscriptions.c
Labels: enhancement, priority-low

#577 Fix typos
  doc/help/man-cupsenable.html
  man/cupsenable.8
  systemv/cupstestppd.c
  vcnet/dns_sd.h
  vcnet/regex/regcomp.c
Labels: bug, priority-low

#555 Manually assign the two char literals instead of a memcpy
  cgi-bin/admin.c
Labels: enhancement, priority-low

#543 Make Letter the default size if the other values do not fit
  tools/ippevepcl.c
Labels: bug, priority-low

#544 Update rxspenser to latest version
  vcnet/regex/main.c
  vcnet/regex/regcomp.c
  vcnet/regex/regerror.c
Labels: bug, priority-low, platform issue

#541 Fix passing wrong variable to cupsGetOption in testcups
  cups/testcups.c
Labels: bug, priority-low

#523 Add documentation for compiling on Fedora
  INSTALL.md
Labels: documentation

#506 Correctly display "Xprinter" instead of Xerox for Xprinter devices
  cups/ppd-attr.c
Labels: bug, priority-low

#462 ci: Add Dependabot to keep GitHub actions up to date
  .github/dependabot.yml
Labels: enhancement

#535 Change (argc < 6 || argc > 7) to (argc != 6 && argc != 7)
  backend/lpd.c
  backend/socket.c
  backend/usb.c
  filter/commandtops.c
  filter/gziptoany.c
  filter/pstops.c
  filter/rastertoepson.c
  filter/rastertohp.c
  filter/rastertolabel.c
  filter/rastertopwg.c
  monitor/bcp.c
  monitor/tbcp.c
Labels: enhancement

#550 Remove redundant Canceled check
  filter/rastertolabel.c
Labels: enhancement

#587 Windows version numbers are unsigned
  cups/usersys.c
Labels: bug, priority-low, platform issue

#580 Log scheme in backend status #579
  scheduler/job.c
Labels: enhancement, priority-low

#597 Have fallback in case GetProcAddress fails
  cups/usersys.c
Labels: enhancement, priority-low, platform issue

#595 Check inheader before checking color space
  filter/rastertopwg.c
Labels: enhancement, priority-low

#592 Mark nonreturning functions as _CUPS_NORETURN
  scheduler/cups-driverd.cxx
Labels: enhancement, priority-low

#589 Remove useless depth argument from static function cups_get_printer_uri
  cups/ppd-util.c
Labels: enhancement, priority-low

#593 Use bitwise OR instead of addition
  backend/usb-libusb.c
  cups/file.c
  cups/http-addr.c
  cups/http-addrlist.c
  cups/http-support.c
  cups/ipp-support.c
  cups/ipp.c
  cups/md5.c
  cups/raster-stream.c
  scheduler/conf.c
  scheduler/type.c
Labels: enhancement, priority-low

#599 PPD for driverless IPP: Poll "media-col-database" separately if needed
  scheduler/ipp.c
Labels: enhancement, priority-low

#528 Fix backchannel status checking bugs
  cups/backchannel.c
Labels: bug, priority-low

#603 Fix-up ORs
  backend/ieee1284.c
  cups/dest-options.c
  scheduler/conf.c
Labels: enhancement, priority-low

#605 Fix bounds of description
  backend/usb-darwin.c
Labels: bug, priority-low
