Repository OpenPrinting/cups, pull requests merged in 2023-06, with the labels that each got.

#704 host_os_name value in config-scripts has changed to 'solaris'
  config-scripts/cups-compiler.m4
  config-scripts/cups-defaults.m4
  config-scripts/cups-directories.m4
  config-scripts/cups-gssapi.m4
  config-scripts/cups-sharedlibs.m4
  config-scripts/cups-threads.m4
Labels: enhancement, priority-low, platform issue

#721 dest.c: Call cupsEnumDests() only if data.name is not NULL (fixes #719)
  cups/dest.c
Labels: bug, priority-high

#726 Regression: Certificate data is corrupted during base64 conversion
  cups/http-support.c
Labels: priority-high

#742 Use "purge-job" instead of "purge-jobs" when canceling a single job
  systemv/cancel.c
Labels: bug, priority-medium
