Repository OpenPrinting/cups, pull requests merged in 2024-04, with the labels that each got.

#674 Create shims to pass to array structures as to not pass incompatible function pointers
  backend/dnssd.c
  backend/ipp.c
  backend/snmp.c
  backend/usb-libusb.c
  cgi-bin/admin.c
  cgi-bin/help-index.c
  cups/array.c
  cups/dest-options.c
  cups/dest.c
  cups/ipp-support.c
  cups/language.c
  cups/libcups2.def
  cups/ppd-cache.c
  cups/ppd-conflicts.c
  cups/ppd-emit.c
  cups/ppd-localize.c
  cups/ppd.c
  cups/pwg-media.c
  cups/string-private.h
  cups/string.c
  cups/testarray.c
  notifier/rss.c
  ppdc/ppdc.cxx
  ppdc/ppdmerge.cxx
  scheduler/auth.c
  scheduler/auth.h
  scheduler/banners.c
  scheduler/client.c
  scheduler/colorman.c
  scheduler/cups-driverd.cxx
  scheduler/cupsd.h
  scheduler/cupsfilter.c
  scheduler/filter.c
  scheduler/job.c
  scheduler/main.c
  scheduler/mime.c
  scheduler/network.c
  scheduler/policy.c
  scheduler/printers.c
  scheduler/process.c
  scheduler/quotas.c
  scheduler/select.c
  scheduler/subscriptions.c
  scheduler/type.c
  scheduler/util.h
  tools/ippeveprinter.c
  tools/ippfind.c
  tools/ipptool.c
Labels: priority-low, platform issue

#929 [Add] Dockerfile and Docker Compose for CUPS setup
  .dockerignore
  .gitignore
  Dockerfile
  INSTALL.md
  docker-compose.yaml
Labels: enhancement, priority-low

#935 scheduler: Fix potential bug when adding new printers (Issue #934)
  scheduler/client.c
Labels: bug, priority-high

#937 scheduler: Fix regression in background thread (Issue #934)
  scheduler/ipp.c
Labels: bug, priority-high
