Repository OpenPrinting/cups, pull requests merged in 2025-04, with the labels that each got.

#1164 locale: Add Georgian translation
  locale/cups_ka.po
Labels: translations

#1161 Update Polish translation
  doc/pl/index.html.in
  locale/cups_pl.po
  templates/pl/add-printer.tmpl
  templates/pl/admin.tmpl
  templates/pl/choose-make.tmpl
  templates/pl/choose-model.tmpl
  templates/pl/choose-serial.tmpl
  templates/pl/choose-uri.tmpl
  templates/pl/class-confirm.tmpl
  templates/pl/class.tmpl
  templates/pl/header.tmpl.in
  templates/pl/help-header.tmpl
  templates/pl/list-available-printers.tmpl
  templates/pl/modify-printer.tmpl
  templates/pl/option-conflict.tmpl
  templates/pl/printer-confirm.tmpl
  templates/pl/printer.tmpl
  templates/pl/printers-header.tmpl
  templates/pl/restart.tmpl
Labels: translations

#1153 Update Dockerfile to Multi-Stage
  Dockerfile
Labels: enhancement, platform issue

#1214 ippfind Avahi API mususe fix and discovery reliability improvement
  tools/ippfind.c
Labels: bug, priority-medium

#1234 Add missing commas in list
  cups/ipp-support.c
Labels: bug, priority-high
